name: Sync from upstream

on:
  schedule:
    - cron: '0 1 * * *'  # every day at 1 AM UTC
  workflow_dispatch:      # allow manual run from Actions tab

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Git user
        run: |
          git config --global user.name 'Nziza GitHub Action'
          git config --global user.email 'your-email@example.com'

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/AGRISENSEPROJECT/AGRISENSE_WEB.git
          git fetch upstream
          git checkout main
          git merge upstream/main
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main
